# Generated by Django 6.0.3 on 2026-05-26 19:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def assign_projects_to_legacy_tasks(apps, schema_editor):
    Task = apps.get_model('core', 'Task')
    Project = apps.get_model('core', 'Project')

    fallback_project = Project.objects.order_by('id').first()
    for task in Task.objects.filter(project__isnull=True):
        project = None
        milestone = getattr(task, 'milestone', None)
        if milestone and getattr(milestone, 'project_id', None):
            project = milestone.project
        elif fallback_project:
            project = fallback_project

        if project:
            task.project_id = project.id
            task.save(update_fields=['project'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_airesult_burnout_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(assign_projects_to_legacy_tasks, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='performancemetric',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='recurringtask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='recurringtask',
            name='project',
        ),
        migrations.RemoveField(
            model_name='taskattachment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskattachment',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline', 'title']},
        ),
        migrations.AlterModelOptions(
            name='tasklog',
            options={'ordering': ['-log_date', '-id']},
        ),
        migrations.RemoveField(
            model_name='airesult',
            name='burnout_score',
        ),
        migrations.RemoveField(
            model_name='airesult',
            name='learning_recommendations',
        ),
        migrations.RemoveField(
            model_name='airesult',
            name='skill_gap',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='task',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='manager_remark',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='progress_after_log',
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airesult',
            name='workload_signal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('overloaded', 'Overloaded'), ('on_leave', 'On Leave')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='weekly_capacity_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed')], default='planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Approval'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='hours_spent',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'team')},
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('notification', 'Notification'), ('comment', 'Comment'), ('review', 'Review'), ('audit', 'Audit')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('message', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/')),
                ('label', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.task')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('leave', 'Leave'), ('task_approval', 'Task Approval')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rework', 'Rework Required')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.employee')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PerformanceMetric',
        ),
        migrations.DeleteModel(
            name='PerformanceReview',
        ),
        migrations.DeleteModel(
            name='RecurringTask',
        ),
        migrations.DeleteModel(
            name='TaskAttachment',
        ),
        migrations.DeleteModel(
            name='TaskComment',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
