# Generated by Django 6.0.3 on 2026-05-30 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_leaverequest_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='task_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
