from django.urls import path

from .views import (
    AnalyticsView,
    ApprovalQueueView,
    AuditLogListView,
    CalendarView,
    DashboardView,
    EmployeeCreateView,
    EmployeeListView,
    EmployeeUpdateView,
    KanbanBoardView,
    LeaveApprovalUpdateView,
    LeaveRequestCreateView,
    LeaveRequestListView,
    NotificationListView,
    PerformanceReviewCreateView,
    PerformanceReviewListView,
    PlanningHubView,
    ProfileUpdateView,
    ProjectCreateView,
    ProjectListView,
    ProjectUpdateView,
    TaskApprovalUpdateView,
    TaskAttachmentCreateView,
    TaskCommentCreateView,
    TaskCreateView,
    TaskDetailView,
    TaskListView,
    TaskLogCreateView,
    TaskUpdateView,
    TeamCreateView,
    TeamListView,
    TeamUpdateView,
    UserAdminUpdateView,
    UserCreateView,
    UserListView,
    UserToggleActiveView,
)

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('users/', UserListView.as_view(), name='user-list'),
    path('users/new/', UserCreateView.as_view(), name='user-create'),
    path('users/<int:pk>/edit/', UserAdminUpdateView.as_view(), name='user-update'),
    path('users/<int:pk>/toggle-active/', UserToggleActiveView.as_view(), name='user-toggle-active'),
    path('teams/', TeamListView.as_view(), name='team-list'),
    path('teams/new/', TeamCreateView.as_view(), name='team-create'),
    path('teams/<int:pk>/edit/', TeamUpdateView.as_view(), name='team-update'),
    path('employees/', EmployeeListView.as_view(), name='employee-list'),
    path('employees/new/', EmployeeCreateView.as_view(), name='employee-create'),
    path('employees/<int:pk>/edit/', EmployeeUpdateView.as_view(), name='employee-update'),
    path('projects/', ProjectListView.as_view(), name='project-list'),
    path('projects/new/', ProjectCreateView.as_view(), name='project-create'),
    path('projects/<int:pk>/edit/', ProjectUpdateView.as_view(), name='project-update'),
    path('planning/', PlanningHubView.as_view(), name='planning-hub'),
    path('tasks/', TaskListView.as_view(), name='task-list'),
    path('tasks/kanban/', KanbanBoardView.as_view(), name='kanban-board'),
    path('tasks/calendar/', CalendarView.as_view(), name='calendar-view'),
    path('tasks/new/', TaskCreateView.as_view(), name='task-create'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('tasks/<int:pk>/edit/', TaskUpdateView.as_view(), name='task-update'),
    path('tasks/<int:pk>/approve/', TaskApprovalUpdateView.as_view(), name='task-approve'),
    path('tasks/<int:pk>/comments/new/', TaskCommentCreateView.as_view(), name='task-comment-create'),
    path('tasks/<int:pk>/attachments/new/', TaskAttachmentCreateView.as_view(), name='task-attachment-create'),
    path('logs/new/', TaskLogCreateView.as_view(), name='tasklog-create'),
    path('analytics/', AnalyticsView.as_view(), name='analytics'),
    path('approvals/', ApprovalQueueView.as_view(), name='approval-queue'),
    path('reviews/', PerformanceReviewListView.as_view(), name='performance-review-list'),
    path('reviews/new/', PerformanceReviewCreateView.as_view(), name='performance-review-create'),
    path('notifications/', NotificationListView.as_view(), name='notification-list'),
    path('leave-requests/', LeaveRequestListView.as_view(), name='leave-request-list'),
    path('leave-requests/new/', LeaveRequestCreateView.as_view(), name='leave-request-create'),
    path('leave-requests/<int:pk>/review/', LeaveApprovalUpdateView.as_view(), name='leave-request-review'),
    path('audit-logs/', AuditLogListView.as_view(), name='audit-log-list'),
]
